Repository Mudlet/Mudlet, pull requests merged in 2018-10, with the labels that each got.

#2018 Fix system messages getting coloured wrong when translated
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2012 Fix GMCP parsing with embedded newlines
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2022 Keep colouring of untranslated text as well
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2017 Fix package exporter crashing when non-English is used
  src/dlgPackageExporter.cpp
  src/dlgPackageExporter.h
  src/ui/dlgPackageExporter.ui
Labels: 1 - Ready for review

#2015 Add feature: visual room creation
  src/T2DMap.cpp
  src/T2DMap.h
Labels: 1 - Ready for review

#2020 Allow enabling MMP map download via GMCP
  src/Host.cpp
  src/Host.h
  src/TMap.cpp
  src/TMap.h
  src/ctelnet.cpp
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#2002 Add feature: copy as image
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/dlgTriggerEditor.h
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#1998 Print to stdout running from console in Windows too
  src/main.cpp
Labels: 2 - Working

#2030 Latest strings for translation
  translations/mudlet.ts
Labels: 1 - Ready for review

#2035 Rename Discord options to use the m prefix for consistency
  src/XMLexport.cpp
  src/XMLimport.cpp
Labels: 1 - Ready for review

#2027 Don't convert forward slashes to backslashes in Windows
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2053 BugFix: remove duplicate entries in resource file
  src/mudlet.qrc
Labels: 1 - Ready for review

#2054 Revise: add unlisted files to QMake project file
  src/mudlet.pro
Labels: 1 - Ready for review

#2055 Revise: improve updateqm.pri file
  translations/translated/updateqm.pri
Labels: 1 - Ready for review, FreeBSD, bugfix, high

#2077 Update ctelnet.c to try to fix ANSI in GMCP
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2074 BugFix: initialise checkBox_showIconsOnMenus in Preferences Dialogue
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2083 Fixed Geyser Label <center> closing tag
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: 1 - Ready for review

#2060 Fix module sync not to crash
  src/Host.cpp
Labels: 1 - Ready for review, high

#2084 Update default IRE mapper to latest version
  src/mudlet-mapper.xml
Labels: 1 - Ready for review

#1903 Suppress debug output from short interval timers
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTimer.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review, bugfix, enhancement

#2080 Added Portuguese as an interface language
  src/mudlet.cpp
  translations/translated/qm.qrc
Labels: 1 - Ready for review

#2066 Update DebugTools.lua to improve display function
  src/mudlet-lua/lua/DebugTools.lua
Labels: 1 - Ready for review, enhancement

#2086 Revise: properly distinguish between two pairs of two languages
  src/mudlet.cpp
Labels: 1 - Ready for review

#2096 Update translation strings
  translations/mudlet.ts
Labels: 1 - Ready for review

#2048 GMCP: determine data separator better
  src/ctelnet.cpp
Labels: 1 - Ready for review
