Repository Mudlet/Mudlet, pull requests merged in 2018-03, with the labels that each got.

#1574 Cleanup: adoption of the edbee editor widget makes THighlighter redundant
  src/CMakeLists.txt
  src/THighlighter.cpp
  src/THighlighter.h
  src/dlgTriggerEditor.cpp
  src/mudlet.pro
Labels: 1 - Ready, low

#1581 BugFix: prevent crashes when GBK/GB18030 decoder fed invalid encoded data
  src/TBuffer.cpp
Labels: 1 - Ready, bugfix, medium

#1583 BugFix: ensure changing out exit door induces a check for modifications
  src/dlgRoomExits.cpp
Labels: 1 - Ready, bugfix, low

#1534 Copy Linux formatter into official binary
  src/TLuaInterpreter.cpp
Labels: 1 - Ready

#1543 Enhance: add ability to set any glyph as a room symbol
  CI/appveyor.install.ps1
  src/T2DMap.cpp
  src/T2DMap.h
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TMap.h
  src/TRoom.cpp
  src/TRoom.h
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/icons/place_of_interest.png
  src/mudlet.pro
  src/mudlet.qrc
  src/ui/glyph_usage.ui
  src/ui/profile_preferences.ui
Labels: 1 - Ready, enhancement
