Repository Mudlet/Mudlet, pull requests merged in 2018-07, with the labels that each got.

#1781 Add windows code signing
  .appveyor.yml
  CI/appveyor.after_success.ps1
Labels: 1 - Ready for review

#1792 BugFix: allow compilation for Windows builds without updater
  .travis.yml
  src/main.cpp
Labels: 1 - Ready for review, Windows, bugfix, low

#1793 BugFix: update a path that is needed for a newer mingw from Windows Qt
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, Windows, bugfix, high

#1794 Cleanup: remove some unwanted QActions from a couple of forms
  src/ui/irc.ui
  src/ui/trigger_editor.ui
Labels: 1 - Ready for review, low

#1777 Allow creating new maps in the map
  src/T2DMap.cpp
  src/T2DMap.h
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#1776 Add mxp supports response
  src/TBuffer.cpp
  src/TBuffer.h
Labels: 1 - Ready for review

#1738 Don't let connection go inactive when not in use
  src/CMakeLists.txt
  src/ctelnet.cpp
  src/ctelnet.h
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.pro
Labels: 1 - Ready for review

#1788 Add expiring temp triggers
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTrigger.cpp
  src/TTrigger.h
Labels: 1 - Ready for review

#1773 Add profile autosave
  src/Host.cpp
  src/Host.h
  src/dlgConnectionProfiles.cpp
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 1 - Ready for review

#1779 Fixed up a few error messages and poor variable names
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1763 Enhance: add control option for icons on menus in absence of Qt respecting system setting
  src/TTextEdit.cpp
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
  src/icons/edit-cut.png
  src/icons/edit-delete-shred.png
  src/icons/edit-select-all.png
  src/icons/edit-web-search.png
  src/icons/run-build-clean.png
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.qrc
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#1803 revise: unify Linux/FreeBSD/macOs keep-alive settings
  src/ctelnet.cpp
  src/ctelnet.h
Labels: 1 - Ready for review, FreeBSD, low

#1804 unify duplicate strings for i18n
  src/dlgRoomExits.cpp
Labels: 1 - Ready for review, bugfix

#1814 BugFix: prevent getGridMode on non-existant area from seg. faulting
  src/TLuaInterpreter.cpp
Labels: bugfix, high

#1815 BugFix: ensure Notepad is always saved on profile close
  src/TConsole.h
  src/dlgNotepad.cpp
  src/dlgNotepad.h
  src/mudlet.cpp
Labels: bugfix, high

#1819 BugFix: include a fail-back icon for the auto-saved profile in Con. Dialog
  src/dlgConnectionProfiles.cpp
  src/icons/document-save.png
  src/mudlet.qrc
Labels: 1 - Ready for review, bugfix, medium

#1808 Big5 support
  src/Host.cpp
  src/TBuffer.cpp
  src/TBuffer.h
  src/ctelnet.cpp
  src/dlgProfilePreferences.cpp
Labels: 3 - Done (Merge hold)

#1820 BugFix: fix faulty log options for new profiles or old profile save files
  src/Host.cpp
  src/Host.h
  src/TConsole.cpp
  src/XMLimport.cpp
Labels: 3 - Done, bugfix, medium

#1821 Fix crash with MXP in 3.11
  src/TBuffer.cpp
Labels: 1 - Ready for review, high

#1833 Delete old Qt version checks in code
  src/ActionUnit.cpp
  src/XMLexport.cpp
Labels: 1 - Ready for review

#1837 Align "no map" message in centre propely
  src/T2DMap.cpp
Labels: 1 - Ready for review

#1838 i18n-ise GUI label creation
  src/T2DMap.cpp
Labels: 2 - Working

#1842 Create module zip if it's not already created when syncing
  src/Host.cpp
Labels: 1 - Ready for review

#1839 Pulled out actions into a mudlet member class variables
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#1832 Fix package exporter to work with async save
  src/Host.cpp
  src/XMLexport.cpp
  src/XMLexport.h
  src/dlgPackageExporter.cpp
Labels: 1 - Ready for review

#1846 Upgrade a few classes to newer Qt connect style
  src/EAction.cpp
  src/T2DMap.cpp
  src/T2DMap.h
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TEasyButtonBar.cpp
  src/TForkedProcess.cpp
  src/TForkedProcess.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMap.cpp
  src/TTextEdit.cpp
  src/TToolBar.cpp
  src/ctelnet.cpp
  src/dlgAliasMainArea.cpp
  src/dlgMapper.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.cpp
  src/dlgTriggerEditor.cpp
  src/dlgTriggersMainArea.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review

#1829 Fix auto-save kicking in and blocking save profile as
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 1 - Ready for review

#1850 BugFix: use Alternative OpenSSLBinary for Windows
  CI/appveyor.install.ps1
Labels: 1 - Ready for review, Windows, bugfix, high

#1862 BugFix: set Server Encoding correctly on auto-loading profiles
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review, bugfix, medium
