Repository Mudlet/Mudlet, pull requests merged in 2018-09, with the labels that each got.

#1948 Ascend tool-tip from filter sub-area
  src/ui/triggers_main_area.ui
Labels: 1 - Ready for review, i18n & l10n

#1936 Add StickMUD support for MMP downloads
  src/TMap.cpp
  src/TMap.h
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#1949 Rename "MUD" to "game" everywhere (except in "Mudlet")
  src/ui/lacking_mapper_script.ui
Labels: 1 - Ready for review

#1945 Fix Speedwalk function to recognise long directions
  src/mudlet-lua/lua/Other.lua
Labels: 1 - Ready for review

#1954 Fix tab completion to work with non-English languages
  src/TCommandLine.cpp
Labels: 1 - Ready for review

#1908 Enhance allow a profile preference dialog per host
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
  src/mudlet.h
  src/updater.cpp
  src/updater.h
Labels: 1 - Ready for review

#1957 Allow downloadFile to follow redirects
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1938 Add a small nudge to upload exported package to Mudlet forums
  src/dlgPackageExporter.cpp
  src/dlgPackageExporter.h
  src/ui/dlgPackageExporter.ui
Labels: 1 - Ready for review, enhancement

#1971 Highlight i18n text using the "highlight" checkbox properly
  src/TTrigger.cpp
Labels: 1 - Ready for review

#1985 Add StickMUD as default MUD
  src/dlgConnectionProfiles.cpp
  src/icons/stickmud_icon.jpg
  src/mudlet.qrc
Labels: 1 - Ready for review

#1950 Add getPlayerRoom() to see the current player location
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review

#1973 Fix UI editor crashing when renaming variable
  src/LuaInterface.cpp
  src/TVar.cpp
  src/TVar.h
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#1836 Fix module sync
  src/Host.cpp
  src/Host.h
Labels: 1 - Ready for review, bugfix

#2000 Fix selectSection not accepting main and returning wrong value
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1988 Fix resetFormat() & system messages to respect users selection
  src/TConsole.cpp
  src/ctelnet.cpp
Labels: 1 - Ready for review
