Repository Mudlet/Mudlet, pull requests merged in 2018-05, with the labels that each got.

#1636 Fix not member not initialised in constructor error
  src/T2DMap.cpp
Labels: 1 - Ready

#1634 Initialise restart button in the constructor
  src/updater.cpp
  src/updater.h
Labels: 1 - Ready

#1635 Fix uninitialised lua_result value
  src/TLuaInterpreter.cpp
Labels: 1 - Ready

#1578 Fixed bug with replaceAll
  src/mudlet-lua/lua/GUIUtils.lua
Labels: 1 - Ready

#1609 Add Lua function getEpoch()
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/CoreMudlet.lua
Labels: 1 - Ready

#1370 BugFix: Coverity 1415093 Using invalid iterator
  src/TLuaInterpreter.cpp
Labels: 1 - Ready

#1637 Add setFont() to allow setting a custom font in a window
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#1586 Add more options for logging
  src/Host.cpp
  src/Host.h
  src/TBuffer.cpp
  src/TConsole.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.cpp
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review, enhancement

#1654 Explicitly state build configs to decrease number of installed packages
  .travis.yml
Labels: 1 - Ready for review

#1661 Fix crash when clicking on the X= icon in variables view
  src/TTreeWidget.cpp
  src/VarUnit.cpp
Labels: 2 - Working, bugfix

#1641 Fixed up a few clazy warnings
  src/AliasUnit.cpp
  src/AliasUnit.h
  src/T2DMap.cpp
  src/TAlias.cpp
  src/TLabel.cpp
  src/ctelnet.cpp
  src/dlgAboutDialog.cpp
  src/dlgColorTrigger.cpp
  src/dlgComposer.cpp
  src/dlgComposer.h
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
  src/dlgMapper.cpp
  src/dlgScriptsMainArea.cpp
  src/dlgSourceEditorArea.cpp
  src/dlgTimersMainArea.cpp
  src/main.cpp
  src/ui/composer.ui
Labels: 2 - Working

#1643 BugFix: allow C key to be used as a key-binding.
  src/TCommandLine.cpp
  src/TCommandLine.h
  src/dlgTriggerEditor.cpp
Labels: 2 - Working

#1670 Fix aliases to work again
  src/TAlias.cpp
Labels: 2 - Working

#1667 Remove redundant xmlexport includes
  src/XMLexport.h
Labels: 2 - Working

#1685 BugFix: solve recently introduce precedential errors
  src/TCommandLine.cpp
Labels: 1 - Ready for review, bugfix, medium

#1668 Redo fix cjk fullwidth character display
  src/CMakeLists.txt
  src/Host.cpp
  src/Host.h
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgConnectionProfiles.cpp
  src/dlgProfilePreferences.cpp
  src/mudlet.pro
  src/ui/profile_preferences.ui
  src/wcwidth.cpp
  src/wcwidth.h
Labels: 1 - Ready for review

#1688 Fix crash closing 1 tab with autosave on
  src/XMLexport.cpp
Labels: 2 - Working, bugfix, high

#1691 Client.GUI server push version numbers are backwards
  src/ctelnet.cpp
Labels: bugfix, low

#1693 Removed debug echo left in downloadFile
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1690 BugFix: Core fix for macOs versions not updating "Save" on Room-Exit dialog
  src/dlgRoomExits.cpp
Labels: 2 - Working, bugfix, medium

#1655 Add coverity scans
  .travis.yml
  CI/travis.compile.sh
  CI/travis.install.sh
  CI/travis.linux.after_success.sh
  CI/travis.linux.install.sh
  CI/travis.osx.after_success.sh
  CI/travis.osx.install.sh
Labels: 2 - Working

#1683 Add support for adding custom fonts in a package
  src/FontManager.cpp
  src/FontManager.h
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/dlgConnectionProfiles.cpp
  src/main.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 2 - Working

#1689 BugFix: Properly handle highlight in tempComplexRegexTrigger
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, bugfix

#1709 Turn off scrollbar when disabled in contructor
  src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
Labels: 1 - Ready for review

#1712 Improve load times for profiles with many packages
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 1 - Ready for review

#1713 Don't create a command line for miniconsoles
  src/TConsole.cpp
Labels: 2 - Working

#1711 Improved code editor search to be massively faster
  src/dlgTriggerEditor.cpp
Labels: 2 - Working

#1699 Improved calcFontSize to take a window parameter as well
  src/TLuaInterpreter.cpp
  src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
  src/mudlet.cpp
  src/mudlet.h
Labels: 2 - Working

#1704 Modernise code - use nullptr, auto, and .empty()
  src/Host.cpp
  src/T2DMap.cpp
  src/T2DMap.h
  src/TBuffer.cpp
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TEasyButtonBar.cpp
  src/TEasyButtonBar.h
  src/TForkedProcess.cpp
  src/TLabel.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMap.cpp
  src/TRoom.cpp
  src/TRoomDB.cpp
  src/TSplitter.h
  src/TTextEdit.cpp
  src/TToolBar.cpp
  src/TToolBar.h
  src/TTrigger.cpp
  src/XMLexport.cpp
  src/ctelnet.cpp
  src/dlgAboutDialog.h
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
  src/dlgIRC.cpp
  src/dlgPackageExporter.cpp
  src/dlgPackageExporter.h
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.h
  src/dlgTriggerEditor.cpp
  src/dlgVarsMainArea.cpp
  src/glwidget.cpp
  src/glwidget.h
  src/main.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review

#1707 Documentation in wiki
  src/TLuaInterpreter.cpp
  src/mudlet-lua/lua/CoreMudlet.lua
  src/mudlet-lua/lua/StringUtils.lua
Labels: 1 - Ready for review

#1714 Don't raise EOR Lua events just like we don't raise them for GA
  src/ctelnet.cpp
Labels: 1 - Ready for review

#1703 Optimised imports in Mudlet.
  src/AliasUnit.cpp
  src/FontManager.cpp
  src/Host.cpp
  src/HostManager.cpp
  src/LuaInterface.cpp
  src/ScriptUnit.cpp
  src/T2DMap.cpp
  src/TArea.cpp
  src/TBuffer.cpp
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TEasyButtonBar.cpp
  src/TForkedProcess.cpp
  src/TLabel.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TRoom.cpp
  src/TRoomDB.cpp
  src/TSplitter.cpp
  src/TSplitterHandle.cpp
  src/TTabBar.cpp
  src/TTextEdit.cpp
  src/TToolBar.cpp
  src/TTreeWidget.cpp
  src/TTrigger.cpp
  src/TimerUnit.cpp
  src/TriggerUnit.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/ctelnet.cpp
  src/dlgAboutDialog.cpp
  src/dlgColorTrigger.cpp
  src/dlgConnectionProfiles.cpp
  src/dlgIRC.cpp
  src/dlgMapper.cpp
  src/dlgNotepad.cpp
  src/dlgPackageExporter.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.cpp
  src/dlgSourceEditorArea.cpp
  src/dlgTriggerEditor.cpp
  src/exitstreewidget.cpp
  src/glwidget.cpp
  src/main.cpp
  src/mudlet.cpp
  src/updater.cpp
Labels: 1 - Ready for review
