Repository Mudlet/Mudlet, pull requests merged in 2018-06, with the labels that each got.

#1720 Modernize code (trivial constructors, no ineffective const, and a few missed for loops)
  src/ActionUnit.h
  src/AliasUnit.h
  src/Host.h
  src/HostManager.h
  src/KeyUnit.cpp
  src/KeyUnit.h
  src/LuaInterface.cpp
  src/ScriptUnit.h
  src/T2DMap.h
  src/TAction.h
  src/TAlias.h
  src/TBuffer.h
  src/TConsole.h
  src/TDebug.cpp
  src/TDebug.h
  src/TEasyButtonBar.h
  src/TKey.h
  src/TMap.h
  src/TRoom.h
  src/TRoomDB.h
  src/TScript.h
  src/TTabBar.h
  src/TTextEdit.h
  src/TTimer.h
  src/TToolBar.h
  src/TTrigger.h
  src/TVar.h
  src/TimerUnit.h
  src/Tree.h
  src/TriggerUnit.h
  src/XMLexport.cpp
  src/XMLexport.h
  src/ctelnet.h
  src/dlgConnectionProfiles.h
  src/dlgMapper.h
  src/dlgProfilePreferences.h
  src/dlgTriggerEditor.h
  src/glwidget.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#1726 Added translations file for crowdin to translate
  translations/mudlet.ts
Labels: 1 - Ready for review

#1743 Re-enable C++14
  src/CMakeLists.txt
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.pro
Labels: 1 - Ready for review

#1741 Show render time only in debug builds
  src/T2DMap.cpp
Labels: 1 - Ready for review

#1696 Improved setBackgroundColor to work with main window
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1752 Version: restore development branch code to non-Release version coding
  CMakeLists.txt
  src/mudlet.pro
Labels: 1 - Ready for review, high

#1748 Update Codeowners for UI review team
  .github/CODEOWNERS
Labels: 1 - Ready for review

#1758 BugFix: correct missing indent of first line of plain text copy
  src/TTextEdit.cpp
Labels: 1 - Ready for review

#1733 Update contribution guidelines for translation PRs
  .github/CONTRIBUTING.md
Labels: 2 - Working

#1757 Enhance: make Mudlet respect icons on dialog buttons system setting
  src/dlgConnectionProfiles.cpp
  src/icons/edit-delete.png
  src/icons/list-add_small.png
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.qrc
  src/ui/connection_profiles.ui
Labels: 1 - Ready for review

#1762 BugFix: get History Scroll Back Keys Working.
  src/TCommandLine.cpp
Labels: 2 - Working, bugfix, high, macOs

#1761 Added context to singleShot timers
  src/Host.cpp
  src/TLuaInterpreter.cpp
  src/dlgTriggerEditor.cpp
  src/updater.cpp
Labels: 1 - Ready for review

#1764 BugFix: try and restore reported key binding recent issues
  src/TCommandLine.cpp
Labels: 0 - In progress, bugfix, high

#1767 Update cocoapods to latest
  CI/travis.osx.install.sh
Labels: 2 - Working

#1754 Optimise for loops in GMCP/MSDP code
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#1770 BugFix: ensure logging settings are saved with profile
  src/XMLexport.cpp
  src/XMLimport.cpp
Labels: 2 - Working, bugfix, medium

#1719 BugFix: correct some issues with background colors not showing on screen
  src/TConsole.cpp
  src/TConsole.h
  src/TTextEdit.h
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review, bugfix, medium

#1786 BugFix: fixes for previous PR1775
  src/mudlet.pro
Labels: 1 - Ready for review, FreeBSD, GNU/Linux, bugfix, high

#1774 BugFix: copy single line text without leading spaces
  src/TCommandLine.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: 1 - Ready for review

#1778 Added getGridMode()
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review
