Repository Mudlet/Mudlet, pull requests merged in 2018-12, with the labels that each got.

#1972 Upgrade pointy to round brackets
  src/dlgRoomExits.cpp
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review, i18n & l10n

#2134 BugFix: fixup some code omissions for Big5 character encoding
  src/TBuffer.cpp
Labels: 1 - Ready for review

#1579 Add text analyser to consoles
  src/Host.cpp
  src/Host.h
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: 0 - Work in progress

#2142 Fix expandAlias()
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, bug, regression

#2153 Remove MMP hardcoding in favour of Client.Map
  src/TMap.cpp
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#2145 Bugfix: correct a typo that provoked a Coverity warning
  src/TTextEdit.cpp
Labels: 3 - Done, bugfix, medium

#2159 Repair to also send aliases
  src/send-text-to-all-games.xml
Labels: 1 - Ready for review
