Repository Mudlet/Mudlet, pull requests merged in 2019-07, with the labels that each got.

#2726 BugFix: prevent loading crash on maps with buggy custom line colors
  src/TRoom.cpp
Labels: 1 - Ready for review, bugfix, high

#2812 Show full path to sound file instead of explanatory tooltip
  src/dlgTriggerEditor.cpp
  src/ui/triggers_main_area.ui
Labels: 1 - Ready for review

#2816 Remove link & mention of Gitter
  src/dlgAboutDialog.cpp
Labels: 1 - Ready for review

#2839 Update Crowdin texts to latest
  translations/mudlet.ts
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#2842 BugFix: render tabs correctly
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: 1 - Ready for review, bugfix, medium

#2843 Update: include newer widechar_width.h which is faster for ASCII characters
  src/TTextEdit.cpp
  src/widechar_width.h
Labels: 1 - Ready for review

#2809 Refactor & upgrade setBorder* & add getBorder*
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review

#2863 Bugfix: add missing header for FreeBSD
  src/mudlet.cpp
Labels: FreeBSD, bugfix

#2872 BugFix: add missing headers for FreeBSD (2)
  src/Host.cpp
  src/ctelnet.cpp
Labels: 1 - Ready for review, FreeBSD
