Repository Mudlet/Mudlet, pull requests merged in 2019-01, with the labels that each got.

#2138 Refactor: use a single enum to classify all TConsole instances
  src/TConsole.cpp
  src/TConsole.h
  src/TTextEdit.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
Labels: 2 - Working

#2166 DataStamp: revise copyright strings for new year (2019)
  src/dlgAboutDialog.cpp
  src/main.cpp
Labels: 1 - Ready for review

#2133 Refactor&Enhance: reduce some spaghetti from TBuffer class...
  src/Host.cpp
  src/Host.h
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#2167 BugFix: allow XMLexport to files with non-Latin1 character filenames
  src/XMLexport.cpp
  src/XMLexport.h
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review, bugfix, i18n & l10n, medium

#2160 Enhance: add lua getMapSelection() function {only covers rooms for now}
  src/T2DMap.cpp
  src/T2DMap.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review

#2173 BugFix: get buttons working in menus on button toolbars
  src/EAction.cpp
  src/EAction.h
Labels: 1 - Ready for review, bugfix, medium

#2174 Refactor: remove all possible remaining old style SIGNAL/SLOT connect(...)s
  src/T2DMap.cpp
  src/TMap.cpp
  src/ctelnet.cpp
  src/dlgMapper.cpp
Labels: 1 - Ready for review

#2182 Fix Mudlet to connect well again
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2183 Refactor: remove redundant external Lua module override
  src/mudlet-lua/lua/LuaGlobal.lua
Labels: 1 - Ready for review, lua only

#2181 Fix Coverity SSL warning
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#1497 TMap allows map versioning
  src/TArea.h
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TMap.h
Labels: 1 - Ready for review

#1893 Text to speech
  .travis.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/HostManager.cpp
  src/HostManager.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/LuaGlobal.lua
  src/mudlet-lua/lua/TTSValues.lua
  src/mudlet.pro
Labels: 1 - Ready for review

#1940 Add generic mapper xml file
  src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
  src/mudlet-lua/lua/generic-mapper/versions.lua
Labels: 1 - Ready for review, enhancement

#2189 Fix saving to use version number correctly in 'development'
  src/TMap.cpp
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#2212 an additional MXP tag <a> to the arensal of MXP tags.
  src/TBuffer.cpp
Labels: 1 - Ready for review

#2219 Fix chance of autoreconnect spam on invalid connection
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2179 Fix variable saving
  src/VarUnit.cpp
  src/VarUnit.h
  src/dlgConnectionProfiles.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 2 - Working

#2228 Enhance: extend getLines(...) to support user created windows
  src/TBuffer.cpp
  src/TLuaInterpreter.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2199 Changed xEcho function to fix cinsertText
  src/mudlet-lua/lua/GUIUtils.lua
Labels: 1 - Ready for review

#2230 Adding call to TriggerUnit::doCleanup() after a script save to avoid stale triggers
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review, bugfix

#2218 Added moveCursorUp and moveCursorDown to GUIUtils
  src/mudlet-lua/lua/GUIUtils.lua
Labels: 1 - Ready for review

#2226 Refactor: move TConsole functions from mudlet class (Part 1)
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2234 Preinstall generic mapper
  src/dlgConnectionProfiles.cpp
  src/generic_mapper_script.xml
  src/mudlet.qrc
Labels: 1 - Ready for review

#2238 Magical quirks to fix MXP issues to make sure it work on various MUDs
  src/Host.cpp
  src/TBuffer.cpp
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2240 Translations: fixup some details reported by translators.
  src/dlgConnectionProfiles.cpp
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
  src/ui/lacking_mapper_script.ui
  src/ui/profile_preferences.ui
  src/ui/room_exits.ui
Labels: 1 - Ready for review

#2242 Update translation strings
  translations/mudlet.ts
Labels: 1 - Ready for review

#2250 BugFix: reset Game Server Echoing flag on disconnect/reconnect
  src/ctelnet.cpp
Labels: 1 - Ready for review, bugfix, medium

#2258 BugFix: correct variation & typo in translation disambiguation comments
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review, bugfix, i18n & l10n

#2256 Refactor almost duplicate error message
  src/ctelnet.cpp
Labels: 1 - Ready for review, i18n & l10n

#2261 Remove colours from trigger patterns
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 1 - Ready for review

#2264 Fix trigger error messages showing wrong pattern #
  src/TTrigger.cpp
Labels: 1 - Ready for review

#2262 Moving-a-Key-into-a-subfolder fix.
  src/KeyUnit.cpp
  src/KeyUnit.h
Labels: 1 - Ready for review
