Repository Mudlet/Mudlet, pull requests merged in 2019-03, with the labels that each got.

#2376 Bug fix freeze when closing self signed certificates on linux
  src/Host.cpp
  src/TLuaInterpreter.cpp
  src/ctelnet.cpp
  src/ctelnet.h
  src/mudlet.cpp
Labels: 1 - Ready for review

#2372 Refactor: provide mProfileName to cTelnet, TConsole and TMap classes
  src/Host.cpp
  src/Host.h
  src/T2DMap.cpp
  src/TConsole.cpp
  src/TConsole.h
  src/TMap.cpp
  src/TMap.h
  src/TRoomDB.cpp
  src/ctelnet.cpp
  src/ctelnet.h
  src/dlgMapper.cpp
  src/glwidget.cpp
Labels: 1 - Ready for review

#2383 BugFix: update CMakeFiles.txt for extra lua file
  CMakeLists.txt
Labels: 1 - Ready for review

#2384 Revise: QGridLayouts' order & resolve names in profile_preferences.ui
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#2387 Revise: update Unicode codepoints width tables to Unicode 11.0
  src/CMakeLists.txt
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/mudlet.pro
  src/wcwidth.cpp
  src/wcwidth.h
  src/widechar_width.h
Labels: 1 - Ready for review

#2390 BugFix: missing header for non-updater platform builds
  src/TTextEdit.cpp
Labels: 1 - Ready for review, FreeBSD, bugfix, medium

#2399 Fix US dictionary to show up on Windows
  CI/copy-non-qt-win-dependencies.ps1
Labels: 1 - Ready for review

#2361 BugFix: redo triggerT-type Indication in editor to return a colour coding
  src/dlgTriggerEditor.cpp
  src/dlgTriggerPatternEdit.cpp
  src/dlgTriggerPatternEdit.h
Labels: 1 - Ready for review

#2408 Improve profile connection message
  src/dlgConnectionProfiles.cpp
Labels: 1 - Ready for review

#2406 Fix punctuation being put on a line of their own when wrapped
  src/TBuffer.cpp
  src/TBuffer.h
Labels: 1 - Ready for review

#2405 Speed up getRoom() a bit
  src/TRoomDB.cpp
  src/TRoomDB.h
Labels: 1 - Ready for review

#2407 Deploy unzipped AppImage alongside zipped
  CI/travis.linux.after_success.sh
Labels: 1 - Ready for review

#2409 Fixed raw postMessage
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2412 Update texts for 3.18 translation
  translations/mudlet.ts
Labels: i18n & l10n

#2416 Remove unused SSL-status boolean from ctelnet
  src/ctelnet.h
Labels: 1 - Ready for review

#2415 Fix potential issues with the main window not existing
  src/TLuaInterpreter.cpp
  src/TTrigger.cpp
Labels: 1 - Ready for review

#2417 Fix 'Eypt' typo
  src/mudlet.cpp
Labels: 1 - Ready for review

#2418 Fix 'Canadia' typo
  src/mudlet.cpp
Labels: 1 - Ready for review

#2419 Fix 'to chose' typos
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#2422 Bug fix prevent crashes when no system spell checker is available
  src/Host.cpp
  src/TCommandLine.cpp
  src/mudlet.cpp
Labels: bugfix, high

#2433 Shortened text for creating buttons
  src/ui/actions_main_area.ui
Labels: 1 - Ready for review

#2437 Shorten text for keybindings
  src/ui/keybindings_main_area.ui
Labels: 1 - Ready for review

#2439 Fix typo in map report tooltip
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#2442 Revise: remove colour palettes from triggers_main_area.ui
  src/ui/triggers_main_area.ui
Labels: 1 - Ready for review

#2443 Revise: remove colour palettes from vars_main_area.ui
  src/ui/vars_main_area.ui
Labels: 1 - Ready for review

#2444 Revise: remove colour palettes from timers_main_area.ui
  src/ui/timers_main_area.ui
Labels: 1 - Ready for review

#2446 Revise: remove colour palettes from system message area & dlgTriggerEditor
  src/dlgTriggerEditor.cpp
  src/ui/system_message_area.ui
Labels: 1 - Ready for review

#2448 Remove unnecessary parenthesis in XMLImport
  src/XMLimport.cpp
Labels: 1 - Ready for review

#2450 Remove unnecessary double-if in selectSection debug
  src/TConsole.cpp
Labels: 1 - Ready for review

#2452 Trim settings tooltip for 'show map errors' to be less verbose
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#2456 Fix an unclosed html header tag in About dialog
  src/dlgAboutDialog.cpp
Labels: 1 - Ready for review

#2454 Check that we have a button before moving it
  src/TToolBar.cpp
Labels: 1 - Ready for review

#2453 Add mSpacer to copy constructor of TMatchState
  src/TMatchState.h
Labels: 1 - Ready for review

#2257 Don't reset other profile's timers with resetProfile()
  src/Host.cpp
  src/TTimer.cpp
  src/TTimer.h
  src/XMLimport.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2459 Remove unnecessary if check in ctelnet decompression
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2451 Improve logic loop readability
  src/TMap.cpp
Labels: 1 - Ready for review

#2470 Enhance: add Event when application Style-sheet set
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, bugfix, enhancement, medium
