Repository Mudlet/Mudlet, pull requests merged in 2019-05, with the labels that each got.

#2507 Enhance: get splitter on right side of editor working + translatable test
  src/XMLimport.cpp
  src/XMLimport.h
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
  src/ui/actions_main_area.ui
  src/ui/color_trigger.ui
  src/ui/source_editor_area.ui
  src/ui/timers_main_area.ui
  src/ui/trigger_editor.ui
  src/ui/triggers_main_area.ui
Labels: 1 - Ready for review

#2529 New texts for version 3.20
  src/mudlet.cpp
  translations/mudlet.ts
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#2530 Update Linux image to Ubuntu 16.06 LTS
  .travis.yml
Labels: 1 - Ready for review, GNU/Linux

#2511 Use Qt 5.12.2 for official Windows releases
  .appveyor.yml
  CI/appveyor.set-environment.ps1
Labels: 1 - Ready for review, Windows

#2528 Show languages' names in their native
  src/mudlet.cpp
Labels: i18n & l10n

#2537 More texts for 3.20
  translations/mudlet.ts
Labels: i18n & l10n

#2545 BugFix: correct argument cock-up and get permTimer(...) working again
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, bugfix, high

#2556 Fix scenario manually-installed packages not upgradable by servers
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2559 BugFix: save & load custom line colors in map format version less than 20
  src/TMap.cpp
  src/TRoom.cpp
Labels: bugfix, medium

#2584 Ensure mMaxRoomIdDigits is initialised in constructor
  src/T2DMap.cpp
Labels: 1 - Ready for review

#2576 Fixed: impossible to add special exit to room 1.
  src/TRoom.cpp
Labels: bugfix

#2586 Optimise copy() and creation of new miniconsoles/userwindows
  src/TBuffer.cpp
Labels: 1 - Ready for review
