Repository Mudlet/Mudlet, pull requests merged in 2019-10, with the labels that each got.

#3124 Enhance: add profile's ANSI colours to Lua color_table
  src/Host.cpp
  src/Host.h
  src/TBuffer.cpp
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/dlgProfilePreferences.cpp
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet.cpp
Labels: 1 - Ready for review, enhancement

#2995 BugFix: correct PR#2976
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2516 Enhance: overhaul stopwatches
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/XMLimport.h
Labels: 1 - Ready for review

#3147 BugFix: fix function names in a couple of copy/paste errors in error texts
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review, bugfix, low

#2889 Revise: only change Encoder for feedTriggers(...) not whole profile
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#3148 BugFix: correct an off-by one error for an empty dictionary file
  src/mudlet.cpp
Labels: 1 - Ready for review, bugfix, low

#3038 Alternative fix trigger highlighting with perl regexp and non-ASCII text
  src/TLuaInterpreter.cpp
  src/TTrigger.cpp
  src/TTrigger.h
Labels: bugfix, medium

#3125 BugFix: handle end of line better for selection by mouse
  src/TTextEdit.cpp
Labels: bugfix, high

#3192 Refactor: remove two `mudlet` non-SLOT methods from `public slot:` part
  src/mudlet.h
Labels: 1 - Ready for review

#3191 BugFix: allow builds without updater code to compile/link
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review, bugfix, high
