Repository Mudlet/Mudlet, pull requests merged in 2019-08, with the labels that each got.

#2729 BugFix: get Qts own translations loading
  .travis.yml
  src/TLuaInterpreter.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.qrc
  src/ui/profile_preferences.ui
Labels: 1 - Ready for review

#2908 Add table.keys utility function
  src/mudlet-lua/lua/TableUtils.lua
Labels: 1 - Ready for review

#2999 Update: drop support for saving to Mudlet 2.1 map format & update default
  src/TLuaInterpreter.cpp
  src/TMap.cpp
Labels: 1 - Ready for review

#3000 BugFix: handle empty SGR...m sequences so they are treated as SGR0m
  src/TBuffer.cpp
Labels: 1 - Ready for review, bugfix, medium

#3012 Support left and right alignments in format strings for Geyser label echos
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: 1 - Ready for review

#3009 Adding c/d/h variants of insertLink, echoPopup, and insertPopup
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
Labels: 1 - Ready for review

#3014 BugFix: restore 3D mapper to FreeBSD
  CMakeLists.txt
  src/ctelnet.cpp
  src/mudlet.pro
Labels: 1 - Ready for review, FreeBSD, bugfix

#2869 Fix 'copy as image' for 2 width characters
  src/TBuffer.cpp
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#3017 Adding format option 's' for geyser labels to add strikethrough
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: 1 - Ready for review
