Repository Mudlet/Mudlet, pull requests merged in 2019-04, with the labels that each got.

#2473 Enhance: New parameter nestflyout=true, use with nestable=true...
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: 1 - Ready for review

#2467 Default-initialise Mudlet event objects before use
  src/Host.cpp
  src/T2DMap.cpp
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TTextEdit.cpp
  src/ctelnet.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review

#2483 Seperate comment from string displayed
  src/T2DMap.cpp
Labels: i18n & l10n

#2485 New texts for version 3.19
  translations/mudlet.ts
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#2486 Revert "Don't reset other profile's timers with resetProfile() (#2257)"
  src/Host.cpp
  src/TTimer.cpp
  src/TTimer.h
  src/XMLimport.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2493 Fix 'then' grammar typo
  src/TRoomDB.cpp
Labels: 1 - Ready for review

#2494 Revise: add a change to TEvent usage to new TEvent instance
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2495 Simplify notepad tooltip
  src/ui/main_window.ui
Labels: 1 - Ready for review

#2496 Simplify manual tooltip
  src/ui/main_window.ui
Labels: 1 - Ready for review

#2449 Fix logic error(?) in map copy
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#2498 BugFix: target room selection for speed-walking was inaccurate
  src/T2DMap.cpp
Labels: 1 - Ready for review, bugfix, medium

#2434 Fix a run-on sentence for editor search box option
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#2501 New StickMUD icon
  src/icons/stickmud_icon.jpg
Labels: 1 - Ready for review

#2502 Add Clessidra as a default MUD
  src/dlgConnectionProfiles.cpp
  src/icons/clessidra.jpg
  src/mudlet.qrc
Labels: 1 - Ready for review

#2504 Update visible Clessidra URL in connection profiles window
  src/dlgConnectionProfiles.cpp
Labels: 1 - Ready for review

#2503 Fix db:add() when adding timestamp fieldsUpdate DB.lua
  src/mudlet-lua/lua/DB.lua
Labels: 1 - Ready for review

#2506 Update: revision of Hunspell dictionary
  src/mudlet.pro
Labels: 1 - Ready for review, FreeBSD

#2480 Refactor: store the Host name and TTimer Id in QTimer properties
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTimer.cpp
  src/TTimer.h
  src/TimerUnit.cpp
  src/TimerUnit.h
  src/Tree.h
  src/XMLimport.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review, bugfix, high, regression

#2479 Added function for calling QTimer remainingTime()
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTimer.cpp
  src/TTimer.h
  src/TimerUnit.cpp
  src/TimerUnit.h
Labels: 1 - Ready for review

#2491 Enhance: add getTextFormat() function to Lua API
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review, enhancement

#2489 Enhance: draw RoomId numbers better in 2D Mapper
  src/T2DMap.cpp
  src/T2DMap.h
Labels: 1 - Ready for review

#2512 Revise: avoid changing the objectName of toolbars/docked windows on layout + add titles to toolbars
  src/TAction.cpp
  src/TAction.h
  src/TEasyButtonBar.cpp
  src/TEasyButtonBar.h
  src/TToolBar.cpp
  src/TToolBar.h
  src/mudlet.cpp
Labels: bugfix

#2524 Remove -lglut for Windows linking
  src/mudlet.pro
Labels: 1 - Ready for review
