Repository Mudlet/Mudlet, pull requests merged in 2019-02, with the labels that each got.

#2268 Fix notification image size in security preferences
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review

#2271 Add new ignore line for generic mapper
  src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
Labels: 1 - Ready for review

#2275 Fix echolink main
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2279 (release-3.17) BugFix: repair loss of trigger colorization
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review, bugfix, high

#2277 Fix Mudlet freezing on Windows when securely-connected host is closed
  src/ctelnet.cpp
  src/ctelnet.h
  src/mudlet.cpp
Labels: 1 - Ready for review

#2280 Only enable HiDPI on Linux on Qt 5.12+
  src/main.cpp
Labels: 1 - Ready for review

#2281 Enhance: Increase resolution of yet more icons
  src/icons/dash-dot-dot-line.png
  src/icons/dash-dot-line.png
  src/icons/dash-line.png
  src/icons/dot-line.png
  src/icons/mudlet_color.png
  src/icons/mudlet_configure.png
  src/icons/mudlet_custom_exit.png
  src/icons/mudlet_custom_exit_properties.png
  src/icons/mudlet_map_download.png
  src/icons/mudlet_room_exits.png
  src/icons/place_of_interest.png
  src/icons/searchOptions-caseSensitive.png
  src/icons/searchOptions-none.png
  src/icons/searchOptions-unspecified.png
  src/icons/solid-line.png
Labels: 1 - Ready for review

#2284 Fix GMCP Discord rich presence
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2269 BugFix: ensure command line spell checker handles non-Latin1 characters
  src/Host.cpp
  src/Host.h
  src/TCommandLine.cpp
  src/TCommandLine.h
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review, enhancement, i18n & l10n

#2297 Make read-only arguments const references
  src/HostManager.cpp
  src/HostManager.h
  src/ScriptUnit.cpp
  src/ScriptUnit.h
  src/TBuffer.cpp
  src/TBuffer.h
  src/TTrigger.cpp
  src/TTrigger.h
  src/TVar.cpp
  src/TVar.h
  src/TimerUnit.cpp
  src/TimerUnit.h
  src/TriggerUnit.cpp
  src/TriggerUnit.h
  src/VarUnit.cpp
  src/VarUnit.h
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 1 - Ready for review

#2294 Pass 'this' argument to lambdas for extra safety
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
  src/updater.cpp
Labels: 1 - Ready for review

#2303 Avoid unnecessary allocations with midRef in TBuffer
  src/TBuffer.cpp
Labels: 1 - Ready for review

#1810 Revise 2D Mapper class to allow better translation
  src/T2DMap.cpp
  src/T2DMap.h
Labels: 1 - Ready for review, enhancement

#1484 Add update available indication to main toolbar (Linux/Windows)
  src/icons/mudlet_important.png
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.qrc
  src/ui/main_window.ui
  src/updater.cpp
  src/updater.h
Labels: 1 - Ready for review, GNU/Linux, Windows, enhancement

#2329 Revise: provide bigger (256x256) mudlet_important.png icon
  src/icons/mudlet_important.png
Labels: 3 - Done

#2314 Don't go out of our way to mask the game name for Discord
  src/Host.cpp
  src/ctelnet.cpp
Labels: 1 - Ready for review

#2312 Fix potential sources of Qt container detachment
  src/Host.cpp
  src/HostManager.cpp
  src/T2DMap.cpp
  src/dlgIRC.cpp
  src/dlgPackageExporter.cpp
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#2332 Limit macOS workaround for 3D mapper to known bad Qt versions
  src/main.cpp
Labels: 1 - Ready for review, macOS

#2345 Use correct variable for relative paths in mudlet.pro
  src/mudlet.pro
Labels: 1 - Ready for review

#2343 BugFix: sort-out Discord Large and Small Icons/Text mixup
  src/Host.cpp
Labels: 1 - Ready for review, bugfix, medium

#2349 Remove redundant code
  src/TBuffer.cpp
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/TTextEdit.cpp
  src/TTimer.cpp
  src/TTreeWidget.cpp
  src/TTrigger.cpp
  src/VarUnit.cpp
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
Labels: 1 - Ready for review

#2348 Remove stray debug echo for language maps
  src/mudlet.cpp
Labels: 1 - Ready for review

#2337 Refactor telnet socket read for unit testing / fuzzing
  src/ctelnet.cpp
  src/ctelnet.h
Labels: 1 - Ready for review

#2360 Improve error msgs for Lua functions
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2364 Fix copy/paste trigger bug in background colour matching
  src/TTrigger.cpp
Labels: 1 - Ready for review

#2363 Fix copy/paste error relating to ignored background colour codes
  src/XMLexport.cpp
Labels: 1 - Ready for review

#2371 Minor string improvements
  src/TLuaInterpreter.cpp
  src/TTrigger.cpp
Labels: 1 - Ready for review

#2369 BugFix: add missing "</span>" in timestamped copy-to-HTML & log files
  src/TBuffer.cpp
Labels: 1 - Ready for review

#2374 Bugfix: fix header includes for compilation on FreeBSD
  src/mudlet.h
Labels: 1 - Ready for review, FreeBSD, bugfix

#2330 Enhance+BugFix: handle 100% complete translation and plurals-only en_US one
  translations/translated/generate-translation-stats.lua
  translations/translated/mudlet_en_US.ts
  translations/translated/updateqm.pri
Labels: 1 - Ready for review, bugfix, enhancement, i18n & l10n
