Repository Mudlet/Mudlet, pull requests merged in 2019-06, with the labels that each got.

#2580 Add support for opening a profile offline
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
  src/mudlet.cpp
  src/mudlet.h
Labels: 1 - Ready for review

#2595 Fix icon duplication and inconsistency in the welcome dialog
  src/dlgConnectionProfiles.cpp
Labels: 1 - Ready for review

#2585 Fix use of unintialised slice.mEchoText when using copy()
  src/TBuffer.cpp
  src/TBuffer.h
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2583 Fix player's current map location changing when renaming to same Host
  src/Host.cpp
Labels: 1 - Ready for review

#2571 Refactor: improve handling of show/hiding some trigger editor controls
  src/dlgTriggerEditor.cpp
  src/ui/triggers_main_area.ui
Labels: 1 - Ready for review

#2597 BugFix: ensure user windows closure when profile is closed if multi-playing
  src/TConsole.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review, bugfix, low

#2599 Fix room deletion crashing in a rare case on Windows
  src/TRoomDB.cpp
Labels: 2 - Working

#2592 Revise: do not pad RoomId numbers with zeros on 2D map
  src/T2DMap.cpp
Labels: 1 - Ready for review

#2603 Align texts for start & end of log files
  src/TConsole.cpp
Labels: i18n & l10n

#2614 Update texts for 3.21 release
  translations/mudlet.ts
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#2566 Update SDK setup
  CI/appveyor.install.ps1
  CI/qt-silent-install.qs
  setup-windows-sdk.ps1
Labels: 1 - Ready for review

#2617 Enable Busted tests inside Mudlet
  CMakeLists.txt
  src/CMakeLists.txt
  src/dlgConnectionProfiles.cpp
  src/mudlet-lua/tests/MudletBusted_spec.lua
  src/mudlet.pro
  src/mudlet.qrc
  src/run-tests.xml
Labels: 1 - Ready for review

#2632 triggereditor - translate name of new triggers
  src/dlgTriggerEditor.cpp
Labels: i18n & l10n

#2633 translate "No patterns defined"
  src/TTrigger.cpp
Labels: i18n & l10n

#2634 Translate more new items' names
  src/dlgTriggerEditor.cpp
Labels: i18n & l10n

#2645 Remove deprecation comment
  src/TVar.cpp
Labels: 1 - Ready for review

#2647 Translate "Socket disconnected" error message
  src/ctelnet.cpp
Labels: i18n & l10n

#2657 New texts for translation
  translations/mudlet.ts
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#2554 BugFix: allow packages with sub-directories & get exporter to report result
  src/XMLexport.cpp
  src/dlgPackageExporter.cpp
  src/dlgPackageExporter.h
  src/mudlet.cpp
  src/ui/dlgPackageExporter.ui
Labels: 1 - Ready for review, bugfix, medium

#1866 Change default command separator to ;;
  src/Host.cpp
Labels: 1 - Ready for review

#2460 Remove unnecessary assignment when reading package/module config
  src/Host.cpp
Labels: 1 - Ready for review

#2455 Improve AliasUnit::findAlias
  src/AliasUnit.cpp
  src/AliasUnit.h
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review

#2457 Improve KeyUnit::findKey
  src/KeyUnit.cpp
  src/KeyUnit.h
  src/TLuaInterpreter.cpp
Labels: 1 - Ready for review
