Repository Mudlet/Mudlet, pull requests merged in 2019-11, with the labels that each got.

#3226 Add simple 2min autosave for notepad contents
  src/dlgNotepad.cpp
  src/dlgNotepad.h
Labels: 1 - Ready for review, enhancement

#3249 Refactor: remove multiple redundent semi-colons following closing braces
  CI/travis.osx.install.sh
  src/Host.cpp
  src/TLuaInterpreter.cpp
  src/ctelnet.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review

#3251 BugFix: revise to remove qmake project file error
  src/mudlet.pro
Labels: 1 - Ready for review, bugfix, medium

#3252 Enhance: add sysBufferShrinkEvent for when a console's buffer is trimmed
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review, enhancement

#3224 Enhance: overhaul stopwatches redux
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/XMLimport.h
  src/mudlet.cpp
Labels: 1 - Ready for review
