Repository Mudlet/Mudlet, pull requests merged in 2020-12, with the labels that each got.

#4310 Revise: remove all `QPalette`s from forms/dialogues
  src/ui/about_dialog.ui
  src/ui/composer.ui
  src/ui/connection_profiles.ui
  src/ui/keybindings_main_area.ui
  src/ui/mapper.ui
  src/ui/profile_preferences.ui
Labels: bugfix, low

#4441 Fixup: insert missing test in TTextCodec methods
  src/TTextCodec.cpp
Labels: bugfix, low

#4440 Revise: select profiles by typing the name, keep profile icons
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
Labels: bugfix, enhancement

#4452 BugFix: prevent export action from being active in Variables editor view
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: bugfix, low

#4445 Enhance: make TConsole scrolling smoother
  src/T2DMap.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/glwidget.cpp
Labels: enhancement

#3151 Add permGroup(name, "key", parent)
  src/TLuaInterpreter.cpp
  src/mudlet-lua/lua/Other.lua
Labels: enhancement

#4509 Revise: suggestion to put default mouse scroll to 3 lines
  src/TTextEdit.cpp
Labels: discussion, enhancement, need more info, needs documentation

#4519 BugFix: correct QRegularExpression warnings on profile save
  src/TAction.h
  src/TConsole.cpp
  src/TKey.h
  src/TMainConsole.cpp
  src/TRoom.cpp
  src/XMLexport.cpp
Labels: bugfix, medium

#4524 BugFix: correct numerical parameter corruption in event handler
  src/TLuaInterpreter.cpp
Labels: bugfix, medium

#4545 BugFix: repair incorrect use of QFont(string) after QFont::toString()
  src/TMap.cpp
Labels: bugfix, low

#4526 Refactor: store special exits and their lock status separately
  src/T2DMap.cpp
  src/TArea.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TRoom.cpp
  src/TRoom.h
  src/dlgRoomExits.cpp
Labels: enhancement
