Repository Mudlet/Mudlet, pull requests merged in 2020-06, with the labels that each got.

#3837 BugFix: attempt to fix some High and Medium Impact Coverity Issues
  src/LuaInterface.cpp
  src/TCommandLine.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TMxpNodeBuilder.cpp
  src/TMxpNodeBuilder.h
  src/TimerUnit.cpp
  src/TimerUnit.h
  src/XMLexport.cpp
  src/XMLexport.h
  src/ctelnet.cpp
  src/ctelnet.h
  src/discord.cpp
  src/dlgRoomExits.cpp
  src/dlgTriggerEditor.cpp
  src/glwidget.cpp
Labels: bugfix

#3838 BugFix: cure setTextFormat(...) colour reversal
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, regression

#3854 BugFix: attempt to solve copy selection problem
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: bugfix, high

#3862 Enhance: improve access to TTabBar elements
  src/TTabBar.cpp
  src/TTabBar.h
Labels: enhancement, medium

#3860 BugFix: prevent empty TBuffer crashes when copying
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: bugfix, high

#3876 BugFix: prevent crashes from recent Coverity Issue fixup
  src/TTabBar.cpp
  src/TTabBar.h
Labels: bugfix, high

#3844 Enhance: make multiView persistent
  src/T2DMap.cpp
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TLabel.cpp
  src/glwidget.cpp
  src/mudlet.cpp
  src/mudlet.h
  src/ui/main_window.ui
Labels: bugfix, enhancement, medium

#3890 Bugfix: prevent build failure with libzip 1.70.0 with no version numbers
  src/dlgPackageExporter.cpp
Labels: bugfix, high

#3942 Revise: prevent multiple connection dialogues
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix

#3927 Remove Default Host code from IRC
  src/dlgIRC.cpp
  src/dlgIRC.h
  src/dlgProfilePreferences.cpp
  src/mudlet.cpp
Labels: 3 - Done, bugfix
