Repository Mudlet/Mudlet, pull requests merged in 2020-02, with the labels that each got.

#3313 Enhance: add the ability to destroy labels without resetting a profile
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: 1 - Ready for review

#3368 BugFix: prevent crash if editor theme tab clicked without a Host anymore
  src/dlgProfilePreferences.cpp
Labels: 1 - Ready for review, bugfix, medium

#3366 Improve tab order in the connection screen
  src/ui/connection_profiles.ui
Labels: a11y

#3370 Label input fields which require an accessibile name
  src/ui/connection_profiles.ui
Labels: a11y
