Repository Mudlet/Mudlet, pull requests merged in 2020-10, with the labels that each got.

#4005 BugFix: try and prevent crashing during highlighting
  src/TTextEdit.cpp
Labels: bugfix, high

#4129 Make dates in filenames sort lexicographically
  src/Host.cpp
  src/TConsole.cpp
Labels: hacktoberfest-accepted

#4095 Enhance: add mapper background and exit color functions
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: enhancement

#4137 Include some large English dicts
  src/mudlet.cpp
Labels: bug, low

#4173 BugFix: fix a CI script error around date calculations
  CI/appveyor.after_success.ps1
  CI/travis.linux.after_success.sh
  CI/travis.osx.after_success.sh
Labels: bugfix, low

#4170 Revise: avoid extra invocations of bash shells in CI scripts
  CI/travis.linux.after_success.sh
  CI/travis.osx.after_success.sh
  CI/travis.set-build-info.sh
  CI/travis.validate_deployment.sh
Labels: bugfix, low

#4089 Revise: improve Windows .ico (multi-image icon files)
  CI/appveyor.after_success.ps1
  icon_1024x1204.png
  icon_dev_1024x1204.png
  icon_ptb_1024x1204.png
  src/CMakeLists.txt
  src/icons/mudlet.ico
  src/icons/mudlet_dev.ico
  src/icons/mudlet_ptb.ico
  src/mudlet.pro
Labels: enhancement

#4201 BugFix: correct copy/paste error in Lua setHexBgColor function
  src/mudlet-lua/lua/GUIUtils.lua
Labels: bugfix, low

#4212 Revise: fixup pan direction arrows in mapper
  src/ui/mapper.ui
Labels: GNU/Linux, bugfix, low
