Repository Mudlet/Mudlet, pull requests merged in 2020-03, with the labels that each got.

#3303 BugFix: force UTF-8 coding for notepad so that all languages work
  src/dlgNotepad.cpp
  src/dlgNotepad.h
Labels: 1 - Ready for review

#3458 Remove stray whitespace from translation
  src/dlgConnectionProfiles.cpp
Labels: 1 - Ready for review, i18n & l10n

#3475 BugFix: don't apply profile s. sheet to preferences when no profile loaded
  src/mudlet.cpp
Labels: 1 - Ready for review, bugfix, high

#3496 BugFix: fix corner case where the lua interpreter is `lua5.1` on Windows
  translations/translated/updateqm.pri
Labels: 1 - Ready for review, Windows, bugfix, medium

#3515 Refactor: only include Noto Color Font where usable (on Linux only)
  src/CMakeLists.txt
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/main.cpp
  src/mudlet.pro
  src/mudlet_fonts_common.qrc
  src/mudlet_fonts_linux.qrc
Labels: 1 - Ready for review

#3497 Refactor: make getMudletLuaDefaultPaths() return actual used details
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/LuaGlobal.lua
  src/mudlet.pro
Labels: 1 - Ready for review, enhancement

#3533 Enhance: allow Mudlet packager to disable variable splash-screens
  CMakeLists.txt
  src/CMakeLists.txt
  src/dlgAboutDialog.cpp
  src/main.cpp
  src/mudlet.pro
Labels: 1 - Ready for review

#3523 BugFix: fix encoding used for logging.
  src/TConsole.cpp
Labels: 1 - Ready for review, bugfix, medium

#3534 Revise: update the development and ptb splash screens again
  src/Mudlet_splashscreen_development.png
  src/Mudlet_splashscreen_ptb.png
  src/Mudlet_splashscreen_working.xcf
  src/mudlet_logo_elements.png
  src/mudlet_logo_text.svg
Labels: 1 - Ready for review, enhancement

#3543 Make searching variables optional (defaults to off)
  src/Host.cpp
  src/Host.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
  src/icons/searchOptions-caseSensitive+withVariables.png
  src/icons/searchOptions-caseSensitive.png
  src/icons/searchOptions-withVariables.png
  src/mudlet.qrc
Labels: 1 - Ready for review
