Repository Mudlet/Mudlet, pull requests merged in 2020-05, with the labels that each got.

#3705 Refactor: remove some obsolete method uses
  src/T2DMap.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TRoom.cpp
  src/TRoomDB.cpp
  src/Tree.h
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.cpp
  src/mudlet.cpp
  src/mudlet.pro
Labels: enhancement

#3699 BugFix: allow CMake builds to find LuaGlobal.lua file (Linux)
  src/TLuaInterpreter.cpp
  src/mudlet.cpp
Labels: GNU/Linux, bugfix, medium

#3653 Localization for Lua
  CI/copy-non-qt-win-dependencies.ps1
  src/mudlet-lua/lua/Other.lua
  src/mudlet-lua/lua/geyser/GeyserAdjustableContainer.lua
  src/mudlet.pro
  translations/lua/mudlet-lua.json
  translations/lua/translated/mudlet-lua_de_DE.json
  translations/lua/translated/mudlet-lua_it_IT.json
  translations/lua/translated/mudlet-lua_ru_RU.json
Labels: i18n & l10n

#3730 BugFix: repair faults introduced by #3705
  src/T2DMap.cpp
  src/TLuaInterpreter.cpp
  src/TRoom.cpp
  src/TRoomDB.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.cpp
  src/mudlet.cpp
Labels: bugfix, high
