Repository Mudlet/Mudlet, pull requests merged in 2020-04, with the labels that each got.

#3550 Refactor: remove pointless QFontLetterSpacing code
  src/TConsole.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: 1 - Ready for review

#3561 Refactor: remove unused `(QList<bool>) TBuffer::dirty`
  src/TBuffer.cpp
  src/TBuffer.h
  src/TTextEdit.cpp
Labels: 1 - Ready for review, enhancement

#3565 Enhance: fixes for CodeFactor
  src/Host.cpp
  src/Host.h
  src/T2DMap.cpp
  src/TBuffer.cpp
  src/TBuffer.h
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TConsole.h
  src/TLabel.cpp
  src/TLuaInterpreter.cpp
  src/TTabBar.cpp
  src/TToolBar.cpp
  src/TTrigger.cpp
  src/ctelnet.cpp
  src/dlgAboutDialog.cpp
  src/dlgIRC.cpp
  src/dlgMapper.cpp
  src/dlgPackageExporter.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomExits.cpp
  src/dlgSystemMessageArea.cpp
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
  src/main.cpp
  src/mudlet.cpp
Labels: 1 - Ready for review

#3566 Enhance: add AppVeyor and CodeFactor status badges to GitHub README.md
  README.md
Labels: 1 - Ready for review, Website matter, enhancement

#3605 BugFix: correct usage of (void) mudlet::show_options_dialog(QString&)
  src/ctelnet.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, medium

#3569 BugFix: fix broken compilation when QT_NO_SSL defined
  src/TMedia.cpp
  src/ctelnet.cpp
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix

#3614 ISO 8601 for PTB date format
  CI/appveyor.set-build-info.ps1
  CI/travis.set-build-info.sh
Labels: enhancement, i18n & l10n

#3610 BugFix: add missing titles to editor toolbars
  src/dlgTriggerEditor.cpp
Labels: bugfix, low

#3609 Enhance: add ability to set title for floating/dockable map window
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/lua/geyser/GeyserMapper.lua
Labels: enhancement

#3616 BugFix: ensure Mudlet external Lua files show in Qt IDE
  src/mudlet.pro
Labels: bugfix, low

#3636 BugFix: fixup failing MacOs CI builds
  3rdparty/luazip/CMakeLists.txt
  3rdparty/luazip/luazip.h
  3rdparty/luazip/luazip.pri
  CI/appveyor.functions.ps1
  CI/appveyor.install.ps1
  CI/travis.osx.after_success.sh
  CI/travis.osx.install.sh
  CMakeLists.txt
  src/CMakeLists.txt
  src/TLuaInterpreter.cpp
  src/mudlet.pro
Labels: bugfix, high, macOS

#3628 BugFix: get translations available again for CMake builds
  translations/translated/CMakeLists.txt
  translations/translated/generate-translation-stats.lua
Labels: bugfix, medium

#3656 BugFix: add missing LIBS variable entry for FreeBSD (QMake only)
  src/mudlet.pro
Labels: FreeBSD, bugfix, medium

#3648 Refactor: allow alternatives for Lua libraries loaded with all profiles
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: enhancement

#3579 Enhance: add support for CP437 encoding
  src/CMakeLists.txt
  src/Host.cpp
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTextCodec.cpp
  src/TTextCodec.h
  src/ctelnet.cpp
  src/ctelnet.h
  src/dlgConnectionProfiles.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.pro
  src/ui/profile_preferences.ui
Labels: enhancement

#3669 Enhance: force GHA Ubuntu build to update + add files to qmake project file
  .github/workflows/build-mudlet.yml
  src/mudlet.pro
Labels: bugfix, high

#3680 Enhance: bodge support for CUF and code for (and discard) ED ESC codes
  src/TBuffer.cpp
Labels: enhancement

#3619 Enhance: allow the use of system provided QtKeyChain packages (both QMAKE & CMAKE)
  CI/travis.osx.after_success.sh
  CI/travis.osx.install.sh
  CMakeLists.txt
  src/CMakeLists.txt
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
  src/mudlet.h
  src/mudlet.pro
Labels: FreeBSD, GNU/Linux, enhancement
