Repository Mudlet/Mudlet, pull requests merged in 2021-10, with the labels that each got.

#5457 More debug and error printing options
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/DebugTools.lua
  src/mudlet-lua/tests/DebugTools_spec.lua
Labels: needs documentation

#5395 BugFix: try and make connectExitStub(...) work as per the API
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TMap.h
  src/TRoom.cpp
  src/TRoom.h
Labels: bugfix, low

#5474 Only enable IRE driver GA bugfix for IRE games
  src/Host.cpp
  src/Host.h
  src/dlgConnectionProfiles.cpp
  src/dlgProfilePreferences.cpp
Labels: hacktoberfest-accepted
