Repository Mudlet/Mudlet, pull requests merged in 2021-11, with the labels that each got.

#5558 Improve: Move showStatistics from TConsole to TMainConsole
  src/TConsole.cpp
  src/TConsole.h
  src/TMainConsole.cpp
  src/TMainConsole.h
Labels: hacktoberfest-accepted

#5560 Improve: Create map / Load map dialog will be again present for empty map
  src/T2DMap.cpp
Labels: hacktoberfest-accepted

#5559 Add: Save/Load map as .json from preferences dialog
  src/dlgProfilePreferences.cpp
Labels: hacktoberfest-accepted

#5561 Improve: Clear edit forms for deleted items
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: hacktoberfest-accepted

#5543 Improve: icons not coloured status text for special exits in exits dialog
  src/dlgRoomExits.cpp
  src/dlgRoomExits.h
  src/exitstreewidget.h
  src/ui/room_exits.ui
Labels: enhancement, hacktoberfest-accepted

#5542 Add events when a speedwalk() is stopped, paused, or finishes (reaches the end)
  src/mudlet-lua/lua/Other.lua
  src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
  src/mudlet-lua/lua/generic-mapper/versions.lua
Labels: needs documentation

#5613 Infrastructure: update PCRE download source to one that still exists
  CI/appveyor.functions.ps1
Labels: bugfix, high, Public infrastructure

#5669 Improvement: c/d/hecho now support strikethrough
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: lua only

#5668 Fix ansi2decho to respect custom colors
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: lua only

#5671 Improvement: c/d/hfeedTriggers, d/hecho2ansi functions now support bold, underline, italics, and strikethrough
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: lua only

#5706 Add: `getProfileStats()` to see # of triggers, aliases, etc from Lua
  src/AliasUnit.cpp
  src/AliasUnit.h
  src/KeyUnit.cpp
  src/KeyUnit.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMainConsole.cpp
  src/TimerUnit.cpp
  src/TimerUnit.h
  src/TriggerUnit.cpp
  src/TriggerUnit.h
Labels: needs documentation
