Repository Mudlet/Mudlet, pull requests merged in 2021-06, with the labels that each got.

#5279 Added mouse menu actions to windows.
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: needs documentation

#5280 Added shortcuts to navigate editor between triggers, aliases, etc.
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: a11y, enhancement, needs documentation

#5288 Enhance: improve line-breaking in Command Line
  src/TCommandLine.cpp
Labels: enhancement
