Repository Mudlet/Mudlet, pull requests merged in 2021-12, with the labels that each got.

#5672 Improvement: expose cecho2ansi and have it work for non-ansi color names as well
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: lua only

#5670 Improvement: ansi2decho now supports italics, underline, and strikethrough
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: lua only

#5715 Fix: windowvista and Mactintosh styles not colouring PushButtons (again)
  src/main.cpp
  src/mudlet.cpp
Labels: bugfix, medium, regression

#5723 Fix: get menu shortcuts and their key sequences working all the time again
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, medium

#5728 Add `getLabelStylesheet()`
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMainConsole.cpp
  src/TMainConsole.h
Labels: needs documentation

#5721 Add `getBackgroundColor()`
  src/Host.cpp
  src/Host.h
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: needs documentation

#5756 Fix allow shortcuts to be updated when active profile changes
  src/ShortcutsManager.cpp
  src/ShortcutsManager.h
  src/mudlet.cpp
Labels: bugfix

#5758 Improve: add a QSpinWidget for adjusting special exit weight in exit dialogue
  src/dlgRoomExits.cpp
  src/dlgRoomExits.h
Labels: enhancement

#4608 Improve: add door symbol display to custom exits lines and to stubs
  src/T2DMap.cpp
  src/T2DMap.h
  src/TMap.cpp
  src/TRoom.cpp
  src/TRoom.h
  src/dlgRoomExits.cpp
  src/ui/room_exits.ui
Labels: enhancement

#5757 Improve: allow profiles to be individually resized when multi-playing
  src/mudlet.cpp
  src/mudlet.h
Labels: enhancement

#5767 Fix: get dark-desktop detection working also on FreeBSD
  src/mudlet.cpp
Labels: bugfix, low, FreeBSD

#5651 Fix: clear Mapper area selector QComboBox on map deletion
  src/TMap.cpp
  src/dlgMapper.cpp
Labels: bugfix, low

#5773 Fix: avoid unbalanced `QPainter` `save()` and `restore()` calls
  src/T2DMap.cpp
Labels: bugfix, low

#5772 Fix: draw stub exits with a circular ending to make them more noticeable
  src/T2DMap.cpp
Labels: bugfix, low

#5769 Add fadein and fadeout to MCMP
  src/TMedia.cpp
  src/TMedia.h
  src/TMediaData.h
Labels: enhancement
