Repository Mudlet/Mudlet, pull requests merged in 2021-02, with the labels that each got.

#4712 Enhance: remove minuscule text from under profile icons
  src/dlgConnectionProfiles.cpp
  src/dlgConnectionProfiles.h
Labels: enhancement

#4742 BugFix: correct regression in getRoomName(...)
  src/TLuaInterpreter.cpp
Labels: bugfix, medium, regression

#4763 Enhance: add mode indication to mapper cursor
  src/T2DMap.cpp
  src/T2DMap.h
Labels: enhancement

#4765 BugFix: correct lua string vs QString replacement argument mixups
  src/TLuaInterpreter.cpp
Labels: bugfix, medium, regression

#4768 BugFix: handling of optional 3rd argument to getRoomUserData
  src/TLuaInterpreter.cpp
Labels: bugfix, medium, regression

#4546 Enhance: import/export map as JSON
  src/T2DMap.cpp
  src/TArea.cpp
  src/TArea.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMap.cpp
  src/TMap.h
  src/TMapLabel.h
  src/TRoom.cpp
  src/TRoom.h
  src/TRoomDB.cpp
  src/TRoomDB.h
  src/XMLimport.cpp
  src/dlgMapper.cpp
  src/dlgProfilePreferences.cpp
  src/dlgRoomSymbol.cpp
  src/glwidget.cpp
  src/mudlet.pro
Labels: enhancement, needs documentation

#4775 Improve exists function, return nil+msg if wrong type provided
  src/TLuaInterpreter.cpp
Labels: discussion

#4811 Don't preinstall "send text to all games" script
  src/dlgConnectionProfiles.cpp
  src/mudlet.qrc
  src/send-text-to-all-games.xml
Labels: needs documentation

#4788 Add getProfileTabNumber()
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: needs documentation

#4650 BugFix: improve handling of TConsole::mSystemMessageBgColor
  src/TConsole.cpp
  src/TMainConsole.cpp
  src/TTextEdit.cpp
Labels: bugfix, low

#4824 BugFix: prevent crashes when clicking on empty maps
  src/Host.cpp
  src/T2DMap.cpp
  src/TConsole.cpp
  src/TRoomDB.h
  src/glwidget.cpp
Labels: bugfix, high, regression

#4864 AdjustableContainerRepositionFinish event, change in AdjustableContainerReposition event
  src/mudlet-lua/lua/geyser/GeyserAdjustableContainer.lua
Labels: needs documentation

#4884 Include the long version as part of snapshots/PTBs
  src/CMakeLists.txt
Labels: regression
