Repository Mudlet/Mudlet, pull requests merged in 2021-01, with the labels that each got.

#4574 BugFix: stop special exits being modified when old format maps are read
  src/TRoom.cpp
Labels: bugfix, low, regression

#4599 rephrase "wrong argument type" errors
  src/TLuaInterpreter.cpp
Labels: enhancement

#4604 Refactor: move labels from TMap to each TArea instance.
  src/CMakeLists.txt
  src/T2DMap.cpp
  src/TArea.cpp
  src/TArea.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMap.cpp
  src/TMap.h
  src/TMapLabel.cpp
  src/TMapLabel.h
  src/TRoomDB.cpp
  src/mudlet.pro
Labels: enhancement

#4653 BugFix: restore long profile names wrapping in connection icons
  src/dlgConnectionProfiles.cpp
Labels: bugfix, medium

#4645 Don't overlap italic text, emojis
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: bugfix, medium

#4679 BugFix: correct mis-use of nullptr to denote no room symbol colour
  src/T2DMap.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
Labels: bugfix, medium

#4687 BugFix: initialise mDlgRoomSymbol so that settng room symbols works again
  src/T2DMap.cpp
  src/T2DMap.h
Labels: bugfix, high, regression

#4693 BugFix: correct merge error from #4604
  src/TMap.cpp
Labels: bugfix, medium

#4694 BugFix: correct missing detail (map label position) from binary map files
  src/TMap.cpp
Labels: bugfix, high, regression

#4716 Mapper: draw room exits that go off the map
  src/TRoom.cpp
Labels: bugfix, low

#4722 BugFix: repair special exits in speedwalks with corrupt names
  src/TMap.cpp
Labels: bugfix, high, regression

#4723 Don't crash when closing Mudlet (PTBs only)
  src/TTimer.cpp
Labels: bugfix, high, regression
