Repository Mudlet/Mudlet, pull requests merged in 2021-04, with the labels that each got.

#5071 BugFix: improve handling of non-map and too new files in profile's map dir
  src/TLuaInterpreter.cpp
  src/TMainConsole.cpp
  src/TMap.cpp
  src/TMap.h
  src/XMLimport.cpp
Labels: bugfix, enhancement

#5091 BugFix: correct typo in OS indentifier macro define
  src/mudlet.cpp
Labels: GNU/Hurd, bugfix, low

#5092 BugFix: restore editor auto-completer to wait for several characters
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
Labels: bugfix, medium

#5128 Coverity: fix issue registered as CID 1503729
  src/TLuaInterpreter.cpp
Labels: bugfix, high, regression

#5155 Enhance: extend getOS() function to include version information
  src/TLuaInterpreter.cpp
  src/mudlet-lua/lua/Other.lua
Labels: enhancement, needs documentation

#5044 avoid top folder duplicate if exporting existing package
  src/dlgPackageExporter.cpp
  src/dlgPackageExporter.h
Labels: needs documentation
