Repository Mudlet/Mudlet, pull requests merged in 2022-10, with the labels that each got.

#6348 Fix: "Don't call QList::begin()/end() on temporary" warning
  src/T2DMap.cpp
Labels: bugfix, medium

#6351 Fix: addMouseEvent causes crash to desktop if display name differs from unique name
  src/TTextEdit.cpp
Labels: bugfix, high

#6359 Fix: allow "set weight" in 2D mapper to work on multiple rooms' weights
  src/T2DMap.cpp
Labels: bugfix, low

#6349 Add: setCommandBackgroundColor, setCommandForegroundColor lua functions
  src/Host.cpp
  src/Host.h
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: needs documentation

#6355 improve Make timestamps persist between sessions
  src/Host.cpp
  src/Host.h
  src/TConsole.cpp
  src/TConsole.h
  src/TTextEdit.cpp
  src/mudlet.cpp
Labels: hacktoberfest-accepted

#6402 Fix: return room list to be within mapper
  src/T2DMap.cpp
Labels: bugfix, medium, regression
