Repository Mudlet/Mudlet, pull requests merged in 2022-01, with the labels that each got.

#5776 Fix: get replays working again
  src/ctelnet.cpp
  src/ctelnet.h
Labels: bugfix, high

#5817 Improve: clean-up/unify and extend item statistics reporting system
  src/AliasUnit.cpp
  src/AliasUnit.h
  src/KeyUnit.cpp
  src/KeyUnit.h
  src/ScriptUnit.cpp
  src/ScriptUnit.h
  src/TLuaInterpreter.cpp
  src/TMainConsole.cpp
  src/TimerUnit.cpp
  src/TimerUnit.h
  src/TriggerUnit.cpp
  src/TriggerUnit.h
Labels: enhancement, i18n & l10n

#5739 Improve: add ScrollBox Gui Element
  src/CMakeLists.txt
  src/Host.cpp
  src/Host.h
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TMainConsole.cpp
  src/TMainConsole.h
  src/TScrollBox.cpp
  src/TScrollBox.h
  src/mudlet-lua/lua/LuaGlobal.lua
  src/mudlet-lua/lua/geyser/GeyserAdjustableContainer.lua
  src/mudlet-lua/lua/geyser/GeyserContainer.lua
  src/mudlet-lua/lua/geyser/GeyserGeyser.lua
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
  src/mudlet-lua/lua/geyser/GeyserScrollBox.lua
  src/mudlet-lua/lua/geyser/GeyserSetConstraints.lua
  src/mudlet-lua/lua/geyser/GeyserUserWindow.lua
  src/mudlet.h
  src/mudlet.pro
Labels: needs documentation

#5827 Improve: Enhance labels to allow animated gif
  src/Host.cpp
  src/Host.h
  src/TLabel.cpp
  src/TLabel.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: needs documentation

#5573 Improve: provide alternative representations of most control characters
  src/Host.cpp
  src/Host.h
  src/TConsole.cpp
  src/TConsole.h
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/ctelnet.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/ui/profile_preferences.ui
Labels: needs documentation

#5762 Fix: enable Multi-view as soon as second profile is started and show all profiles when it is active and further profiles are started
  src/TMainConsole.cpp
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, low, regression

#5359 Fix: use better form for a couple of translatable texts.
  src/dlgPackageExporter.cpp
  src/dlgPackageManager.cpp
  src/ui/dlgPackageExporter.ui
  src/ui/package_manager.ui
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n, translations

#5874 Fix: make logging have a per profile persistent control method
  src/Host.cpp
  src/Host.h
  src/TMainConsole.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, high

#5532 Fix: enable restoration of editor toolbars even if both get hidden
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: bugfix, low

#5848 Infrastructure: Add simple option to use Clang sanitizers
  .github/workflows/update-3rdparty.yml
  3rdparty/cmake-scripts/sanitizers.cmake
  src/CMakeLists.txt
Labels: needs documentation

#5887 Fix: prevent bogus NAWS and window resize events on tab changes
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
Labels: bugfix, high, regression

#5881 Add additional 2string functions for stripping formatting codes from c/d/hecho formatted text
  src/mudlet-lua/lua/GUIUtils.lua
  src/mudlet-lua/tests/GUIUtils_spec.lua
Labels: needs documentation

#5921 Improve: setMoviePaused should only ever pause, not unpause as well
  src/TLuaInterpreter.cpp
  src/mudlet-lua/lua/geyser/GeyserLabel.lua
Labels: needs documentation

#5929 Fix: correctly save fore/background color and transparency of labels in JSON map files
  src/TArea.cpp
Labels: bugfix, low
