Repository Mudlet/Mudlet, pull requests merged in 2022-11, with the labels that each got.

#6382 Add: sysBufferShrinkEvent for when a console's buffer is trimmed
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: enhancement, needs documentation

#6405 Fix: ensure area selector widget is updated after map is loaded
  src/Host.cpp
Labels: bugfix

#6383 Add: support for OpenBSD operating system
  CMakeLists.txt
  src/Announcer.h
  src/AnnouncerUnix.cpp
  src/CMakeLists.txt
  src/Host.cpp
  src/Host.h
  src/ctelnet.cpp
  src/dlgProfilePreferences.cpp
  src/mudlet.cpp
  src/mudlet.h
  src/mudlet.pro
  translations/translated/updateqm.pri
Labels: OpenBSD

#6330 Fix crashing when a TToolBar (floating/dockable toolbar) is turned into a TEasyButtonBar (fixed around main console)
  src/ActionUnit.cpp
  src/Host.cpp
  src/Host.h
Labels: bugfix, high

#6285 Add: temporary map labels
  src/CMakeLists.txt
  src/Host.cpp
  src/T2DMap.cpp
  src/TArea.cpp
  src/TArea.h
  src/TConsole.cpp
  src/TLuaInterpreter.cpp
  src/TMainConsole.cpp
  src/TMap.cpp
  src/TMap.h
  src/TMapLabel.h
  src/TRoom.cpp
  src/lua-function-list.json
  src/mudlet.pro
  src/ui/map_label.ui
Labels: needs documentation

#6422 Infrastructure: resolve merge conflict
  src/T2DMap.cpp
  src/dlgRoomProperties.cpp
Labels: bugfix, high

#6409 Add: Prompt for secure connection choice
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/ctelnet.cpp
  src/ctelnet.h
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: needs documentation

#6353 add Ctrl+F shortcut to search main window, and rework Ctrl-C
  src/TCommandLine.cpp
Labels: needs documentation

#6401 Improve: allow `isActive(...)` and `exists(...)` to use an ID number
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: needs documentation
