Repository Mudlet/Mudlet, pull requests merged in 2022-04, with the labels that each got.

#6072 Fix: repair Windows CI build failures
  .github/workflows/dangerjs.yml
  CI/appveyor.functions.ps1
Labels: bugfix, high

#6075 Fix: add handling of new features element in IRE Muds XML map format
  src/XMLimport.cpp
  src/XMLimport.h
Labels: bugfix, enhancement

#6074 Add: setConfig and an initial set of values
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/dlgMapper.cpp
  src/dlgMapper.h
  src/mudlet-lua/lua/Other.lua
Labels: needs documentation
