Repository Mudlet/Mudlet, pull requests merged in 2022-12, with the labels that each got.

#6451 Fix: update GCC version used in CI builds
  .github/workflows/build-mudlet.yml
  .github/workflows/codeql-analysis.yml
  CI/travis.linux.install.sh
Labels: bugfix, high

#6468 Fix: limit maximum replay speed up multiplier
  src/mudlet.cpp
Labels: bugfix, medium

#6467 Add: setConfig("compactInputLine", true/false)
  src/TCommandLine.cpp
  src/TLuaInterpreter.cpp
Labels: needs documentation

#6476 Fix: clean up after some right-click (context) menus
  src/T2DMap.cpp
  src/TTextEdit.cpp
Labels: bugfix, low
