Repository Mudlet/Mudlet, pull requests merged in 2023-03, with the labels that each got.

#6601 Improve: update mudlet_en_US numerus translations 2023/03
  translations/translated/mudlet_en_US.ts
Labels: high, i18n & l10n

#6605 Infrastructure: try to fix failure to update dblsql feed with PTB builds
  .github/workflows/link-ptbs-to-dblsqd.yml
  .github/workflows/tag-pull-requests.yml
  src/mudlet.pro
Labels: bugfix, medium

#6603 Fix: get translations working on command line actions
  src/main.cpp
  src/mudlet.cpp
Labels: bugfix, i18n & l10n

#6502 Fix: ensure input line does not lose focus on switching between profiles
  src/ActionUnit.cpp
  src/Host.cpp
  src/Host.h
  src/TAction.cpp
  src/TCommandLine.cpp
  src/TCommandLine.h
  src/TConsole.cpp
  src/TConsole.h
  src/TDockWidget.cpp
  src/TDockWidget.h
  src/TLabel.cpp
  src/TLabel.h
  src/TMainConsole.cpp
  src/TTextEdit.cpp
  src/TToolBar.cpp
  src/dlgProfilePreferences.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, high

#6509 Add Command Line Tab Complete blacklist
  src/TCommandLine.cpp
  src/TCommandLine.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
Labels: enhancement, needs documentation

#6616 Fix: correct search for Lua interpreter for qmake builds
  translations/translated/CMakeLists.txt
  translations/translated/updateqm.pri
Labels: bugfix, low

#6620 Fix: restore generation of `sysWindowsResizeEvent` when borders are changed
  src/Host.cpp
  src/Host.h
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
Labels: bugfix, regression

#6640 Infrastructure: update Noto Color Emoji font to Unicode 15.0 v2.038
  src/fonts/noto-color-emoji-2021-11-01-v2.034/LICENSE
  src/fonts/noto-color-emoji-2021-11-01-v2.034/README
  src/fonts/noto-color-emoji-2022-09-16-v2.038/LICENSE
  src/main.cpp
  src/mudlet_fonts_linux.qrc
Labels: enhancement, Public infrastructure

#6644 Fix: prevent right clicking in error console moving focus to main window
  src/TConsole.cpp
  src/TTextEdit.cpp
Labels: bugfix, regression

#6645 Fix: prevent user map menus being deleted prematurely
  src/T2DMap.cpp
Labels: bugfix, regression

#6684 Fix: buttons in menus not working (4.17)
  src/TAction.cpp
Labels: bugfix, high, regression
