Repository Mudlet/Mudlet, pull requests merged in 2023-05, with the labels that each got.

#6863 Fix: a wrong function name and a bogus error return value in setScript(...)
  src/TLuaInterpreter.cpp
Labels: bugfix

#6873 Improve: enabling and disabling all but main command line
  src/TLuaInterpreter.cpp
Labels: bugfix, enhancement, high

#6848 Add: option to disable scrolling on miniconsoles
  src/TBuffer.cpp
  src/TCommandLine.cpp
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTextEdit.cpp
  src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
Labels: needs documentation
