Repository Mudlet/Mudlet, pull requests merged in 2023-02, with the labels that each got.

#6511 Fix: restore buttons & timing screen if main command line hidden & restored
  src/TConsole.cpp
Labels: bugfix, low

#6486 Improve: ensure whole item is selected in room properties QComboBoxes
  src/dlgRoomProperties.cpp
  src/dlgRoomProperties.h
Labels: enhancement

#6543 Infrastructure: improve TLabel creation
  src/TLabel.cpp
  src/TLabel.h
  src/TMainConsole.cpp
Labels: low

#6547 Infrastrcture: Initialize TLuaInterpreter variables before access
  src/TLuaInterpreter.cpp
Labels: low

#5895 Fix: Unknown nested elements in XML packages elements (like Host etc.) will cause erasure of settings
  src/XMLimport.cpp
  src/XMLimport.h
Labels: bugfix, high

#6541 Fix: Show Client.GUI GMCP in Lua interpreter
  src/ctelnet.cpp
Labels: bugfix, low

#6530 Fix: off-by-one-million error in third argument to Lua `showNotification()`
  src/TLuaInterpreter.cpp
Labels: bugfix, low, needs documentation

#6564 add getConfig and fix return value of setConfig
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/mudlet-lua/lua/Other.lua
Labels: needs documentation

#6573 Fix: ensure 3D push-button is updated if mode is changed by `setConfig(...)`
  src/dlgMapper.cpp
  src/dlgMapper.h
Labels: bugfix, low

#6582 fix: launch Mudlet anyway when given unknown command line options
  src/main.cpp
Labels: bugfix, high

#6457 Add: support for EUC-KR Server encoding
  src/Host.cpp
  src/Host.h
  src/TBuffer.cpp
  src/TBuffer.h
  src/ctelnet.cpp
  src/dlgProfilePreferences.cpp
  src/mudlet.cpp
Labels: enhancement, 0 - On hold, i18n & l10n
