Repository Mudlet/Mudlet, pull requests merged in 2023-12, with the labels that each got.

#7019 Add: Gif tracking for profile statistics and getProfileStats()
  src/CMakeLists.txt
  src/GifTracker.cpp
  src/GifTracker.h
  src/Host.cpp
  src/Host.h
  src/TLuaInterpreter.cpp
  src/TMainConsole.cpp
  src/mudlet.pro
Labels: 🙋 Bounty claim

#6946 Improve: add separate tooltip to insertPopup() and other functions (alternative)
  src/TLinkStore.cpp
  src/TLinkStore.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/mudlet.pro
Labels: enhancement

#6726 Improve: add ancestors functions
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TTimer.cpp
  src/TTimer.h
  src/TimerUnit.cpp
  src/Tree.h
  src/XMLimport.cpp
  src/dlgTriggerEditor.cpp
Labels: bugfix, medium

#7022 Improve: Hold ctrl while dragging to install as module
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/lua-function-list.json
  src/mudlet-lua/lua/Other.lua
  translations/lua/mudlet-lua.json
Labels: 🙋 Bounty claim

#7041 Improve: Add default template for new package in package exporter
  src/dlgPackageExporter.cpp
  src/ui/dlgPackageExporter.ui
Labels: 🙋 Bounty claim

#7024 Fix: enableTrigger() does not work always on groups
  src/Tree.h
Labels: 🙋 Bounty claim

#7039 Fix: Wordwrap for MiniConsole and echo
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
Labels: 🙋 Bounty claim

#7055 Fix: Accept JSON int for Client.GUI.version
  src/ctelnet.cpp
Labels: needs documentation
