Repository Mudlet/Mudlet, pull requests merged in 2023-04, with the labels that each got.

#6709 Fix: do not use the profile name, url or port in game save files
  src/Host.cpp
  src/Host.h
  src/XMLimport.cpp
Labels: bugfix, low

#6719 Fix: allow search highlighting to be undone
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
  src/TConsole.h
  src/TTextEdit.cpp
  src/TTextEdit.h
Labels: bugfix, medium

#6712 Fix: instability when auto-loading multiple profiles
  src/Host.cpp
  src/Host.h
  src/TCommandLine.cpp
  src/mudlet.cpp
Labels: bugfix, regression

#6741 Infrastructure: update development builds to version 4.17.2
  CMakeLists.txt
  src/mudlet.pro
Labels: Public infrastructure

#6731 Fix: ensure map loading occurs at correct point in profile initialiation
  src/Host.cpp
  src/Host.h
  src/mudlet.cpp
Labels: bugfix, low

#6760 Fix: get MSYS2/Mingw-w64 builds compiling
  src/uiawrapper.h
Labels: bugfix, OS:Windows

#6715 Add: allow historical maps to be selected in settings
  src/TMap.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/icons/application-json.png
  src/icons/application-xml.png
  src/mudlet.qrc
  src/ui/profile_preferences.ui
Labels: enhancement, bounty-30

#6773 Infrastructure: update the en_US translations to include recent text changes
  translations/translated/mudlet_en_US.ts
Labels: i18n & l10n

#6537 Improve: Remove obsolete context menu options
  src/T2DMap.cpp
Labels: enhancement

#6789 Fix: make delete map button function better
  src/T2DMap.cpp
  src/TLuaInterpreter.cpp
  src/TMap.cpp
  src/TMap.h
  src/dlgMapper.cpp
  src/dlgMapper.h
  src/dlgProfilePreferences.cpp
Labels: bugfix, low
