Repository Mudlet/Mudlet, pull requests merged in 2024-10, with the labels that each got.

#7450 Add: Quick clear input-line functionality
  src/TCommandLine.cpp
  src/TCommandLine.h
Labels: needs documentation

#7445 Fix: Remove encoding from NEW-ENVIRON/MNES
  src/ctelnet.cpp
Labels: Hacktoberfest

#7454 Fix: include time-stamps in NAWS calculations
  src/TBuffer.cpp
  src/TBuffer.h
  src/TTextEdit.cpp
  src/ctelnet.cpp
Labels: Hacktoberfest

#7457 Add: extend GUI Languages to support Hebrew
  src/mudlet.cpp
  translations/lua/translated/mudlet-lua_he_IL.json
  translations/translated/mudlet_he_IL.ts
  translations/translated/qm.qrc
Labels: Hacktoberfest

#7459 Fix: Use ccache for macOS Github CI builds
  .github/workflows/build-mudlet.yml
Labels: Hacktoberfest

#7461 Fix: when closing multiple profiles wait for quiescence before proceeding
  src/mudlet.cpp
Labels: bugfix, high, Hacktoberfest

#7466 Fix: prevent crashes on closing a profile with dockable toolbars or mapper
  src/T2DMap.cpp
  src/TToolBar.cpp
Labels: Hacktoberfest

#7468 Fix: repair missing libraries for 32 bit Windows builds
  CI/package-mudlet-for-windows.sh
Labels: bugfix, high, OS:Windows, Hacktoberfest

#7456 Improve: Reduce Client.GUI Console Messages
  src/ctelnet.cpp
  src/ctelnet.h
Labels: Hacktoberfest

#7465 Fix: update console after clearWindow(...)
  src/Host.cpp
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreterUI.cpp
  src/TMainConsole.cpp
  src/TMainConsole.h
Labels: Hacktoberfest

#7475 Improve: AdjustableContainer:setTitle() formatting codes in documentation
  src/mudlet-lua/lua/geyser/GeyserAdjustableContainer.lua
Labels: Hacktoberfest

#7474 Fix: don't display titlebar in certain locked positions
  src/mudlet-lua/lua/geyser/GeyserAdjustableContainer.lua
Labels: Hacktoberfest

#7476 Improve: New event sysSettingChanged
  src/Host.cpp
Labels: Hacktoberfest

#7469 Improve: MacOS arm64 builds
  .github/workflows/build-mudlet.yml
  3rdparty/discord/rpc/lib/libdiscord-rpc.dylib
  3rdparty/our-vcpkg-dependencies/vcpkg-arm64-osx-dependencies
  CI/travis.after_success.sh
  CI/travis.osx.after_success.sh
Labels: Hacktoberfest

#7487 Improve: New x86_64 MacOS runner
  .github/workflows/build-mudlet.yml
  CMakeLists.txt
  src/mudlet.pro
Labels: Hacktoberfest

#7470 Improve: make main menu items be disabled the same as main toolbar buttons
  src/mudlet.cpp
  src/mudlet.h
  src/ui/main_window.ui
Labels: Hacktoberfest

#7490 Infrastructure: Make Linux PTB linking more resilient
  .github/workflows/link-ptbs-to-dblsqd.yml
Labels: Hacktoberfest

#7498 Add multiline param triggers
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TLuaInterpreterMudletObjects.cpp
  src/TTrigger.cpp
  src/TTrigger.h
  src/dlgTriggerEditor.cpp
Labels: Hacktoberfest

#7488 Infrastructure: continue work on macOS arm64 PTBs
  .github/workflows/build-mudlet.yml
  .github/workflows/link-ptbs-to-dblsqd.yml
  CI/travis.osx.after_success.sh
Labels: Hacktoberfest

#7496 Improve: remove unused pattern 'type' box in aliases UI
  src/ui/aliases_main_area.ui
Labels: Hacktoberfest

#7486 Fix: allow running PTB builds on demand
  .github/workflows/build-mudlet.yml
  CI/travis.set-build-info.sh
Labels: Hacktoberfest
