Repository Mudlet/Mudlet, pull requests merged in 2024-12, with the labels that each got.

#7555 improve "move to area" to preselect current shown area in combobox
  src/T2DMap.cpp
  src/dlgMapper.cpp
  src/dlgMapper.h
Labels: 🙋 Bounty claim

#7547 Improve: mark overlapping rooms in 2D mapper
  src/Host.cpp
  src/Host.h
  src/T2DMap.cpp
  src/T2DMap.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/main.cpp
  src/ui/profile_preferences.ui
Labels: enhancement

#7559 Fix: restore ability to load older profile versions
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: bugfix, medium

#7561 Fix: install Qt translations for Windows builds
  CI/setup-windows-sdk.sh
Labels: bugfix, OS:Windows, i18n & l10n

#7572 Fix: Duplication of module contents after saving with module running on multiple loaded profiles
  src/Host.cpp
Labels: 🙋 Bounty claim

#7593 Fix: show room symbols at smaller sizes
  src/T2DMap.cpp
Labels: 🙋 Bounty claim

#7598 Add: give map label text the ability to have an outline
  src/T2DMap.cpp
  src/TLuaInterpreterMapper.cpp
  src/TMap.cpp
  src/TMap.h
  src/TMapLabel.h
  src/dlgMapLabel.cpp
  src/dlgMapLabel.h
  src/ui/map_label.ui
Labels: 🙋 Bounty claim

#7589 fix: copy to clipboard after double clicking on a word
  src/TTextEdit.cpp
Labels: 🙋 Bounty claim

#7605 Improve: report Mudlet client name and version over MSDP when enabled
  src/ctelnet.cpp
Labels: 🙋 Bounty claim
