Repository Mudlet/Mudlet, pull requests merged in 2024-08, with the labels that each got.

#7375 Add portable support
  src/dlgProfilePreferences.cpp
  src/dlgTriggerEditor.cpp
  src/main.cpp
  src/mudlet.cpp
  src/mudlet.h
  src/utils.h
Labels: needs documentation, 🙋 Bounty claim

#7391 Fix: 64bit Mudlet on Windows does not play sounds
  CI/setup-windows-sdk.sh
  src/main.cpp
Labels: 🙋 Bounty claim

#7184 Improve: speed up bulk room creation
  src/TArea.cpp
  src/TArea.h
  src/TLuaInterpreterMapper.cpp
  src/TMap.cpp
  src/TMap.h
  src/TRoom.cpp
  src/TRoom.h
  src/TRoomDB.cpp
Labels: needs documentation

#7395 improve: Consolidate profile loading logic
  src/dlgConnectionProfiles.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: 🙋 Bounty claim

#7406 Fix: crash when running `map update` at once across several profiles
  src/XMLexport.cpp
Labels: 🙋 Bounty claim
