Repository Mudlet/Mudlet, pull requests merged in 2025-08, with the labels that each got.

#7998 Improve: default to hidden toolbar (huge buttons) by default
  src/mudlet.cpp
  src/mudlet.h
Labels: needs documentation

#7997 Improve: don't show connection status in tabs by default and add an API option
  src/TLuaInterpreter.cpp
  src/dlgProfilePreferences.cpp
  src/dlgProfilePreferences.h
  src/mudlet.cpp
  src/mudlet.h
  src/ui/profile_preferences.ui
Labels: needs documentation

#8015 Infrastructure: move from squirrel.windows to Clowd.squirrel (PR FORM)
  .github/workflows/build-mudlet-win.yml
  CI/deploy-mudlet-for-windows.sh
  CI/package-mudlet-for-windows.sh
  CI/register-windows-release.sh
  CI/travis.osx.after_success.sh
Labels: bugfix, high, Private infrastructure, 🙋 Bounty claim

#8022 Infrastructure: get link-ptbs-to-dblsqd workflow working again
  .github/workflows/build-mudlet-win.yml
  .github/workflows/link-ptbs-to-dblsqd.yml
  CI/deploy-mudlet-for-windows.sh
  CI/register-windows-release.sh
Labels: bugfix, high, Private infrastructure, 🙋 Bounty claim

#8026 Add: openMudletHomeDir()
  src/mudlet-lua/lua/Other.lua
Labels: needs documentation

#7881 Fix: Show sent commands -> Always / Script Controlled / Never
  src/Host.cpp
  src/Host.h
  src/TCommandLine.cpp
  src/TLuaInterpreter.cpp
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: needs documentation

#8062 Fix: partial revert of change to link-ptbs-to-dblsqd GH Actions workflow
  CI/register-windows-release.sh
Labels: high, OS:Windows, Private infrastructure

#8028 Infrastructure: Verify documentation is available for new features
  .github/workflows/check_pr_labels.yml
Labels: needs documentation

#8056 add: multi-select functionality in script editor
  src/TTreeWidget.cpp
  src/dlgTriggerEditor.cpp
  src/dlgTriggerEditor.h
Labels: 🙋 Bounty claim

#8131 Fix: options overflow when option is higher than 126
  src/ctelnet.cpp
  src/ctelnet.h
Labels: 0 - Waiting for other PR Merge
