Repository Mudlet/Mudlet, pull requests merged in 2025-05, with the labels that each got.

#7836 Fix: correct the locale used when generating translations
  translations/translated/CMakeLists.txt
  translations/translated/updateqm.pri
Labels: bugfix, low

#7842 Fix: ensure we include the right Lua header files
  CI/deploy-mudlet-for-windows.sh
  CI/package-mudlet-for-windows.sh
  src/LuaInterface.cpp
  src/LuaInterface.h
  src/TKey.h
  src/TLuaInterpreter.h
  src/TVar.h
  src/dlgVarsMainArea.cpp
  src/mudlet.pro
  test/TLuaInterfaceTest.cpp
Labels: bugfix, high, OS:Windows

#7739 Improve clicking around the map
  src/T2DMap.cpp
Labels: 🙋 Bounty claim

#7870 Add: sysConsoleSizeChanged event triggered on resize and timestamps toggling
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
  src/TConsole.h
  src/TLuaInterpreter.cpp
  src/TLuaInterpreter.h
  src/TLuaInterpreterUI.cpp
  src/TTextEdit.cpp
  src/TTextEdit.h
  src/ctelnet.cpp
  src/dlgTriggerEditor.cpp
  src/mudlet.cpp
  src/mudlet.h
Labels: needs documentation
