Repository Mudlet/Mudlet, pull requests merged in 2025-03, with the labels that each got.

#7762 Fix: incorrect initialisation of Host::mEnableMSDP
  src/Host.h
Labels: bugfix, low

#7610 Fix: slice up QKeySequences correctly for Mute/Unmute
  src/mudlet.cpp
Labels: bugfix, medium

#7781 Improve: report SGR details that Mudlet does not currently reproduce
  src/TBuffer.h
  src/TLuaInterpreterUI.cpp
Labels: enhancement

#7794 Fix: put Qt translations in correct location
  CI/package-mudlet-for-windows.sh
Labels: bugfix, medium, OS:Windows

#7729 Fix packages not behaving as same as modules
  src/ScriptUnit.cpp
  src/TScript.cpp
  src/dlgTriggerEditor.cpp
Labels: 🙋 Bounty claim
