Repository Mudlet/Mudlet, pull requests merged in 2025-02, with the labels that each got.

#7679 Adds hanging indent on wrapped lines
  src/Host.cpp
  src/Host.h
  src/TBuffer.cpp
  src/TBuffer.h
  src/TConsole.cpp
  src/TConsole.h
  src/XMLexport.cpp
  src/XMLimport.cpp
  src/dlgProfilePreferences.cpp
  src/ui/profile_preferences.ui
Labels: 🙋 Bounty claim

#7690 Fix: prevent crashes when shortcuts are empty
  src/dlgProfilePreferences.cpp
Labels: bugfix, high

#7686 Improve: add processor compilation details to getOS() output
  src/TLuaInterpreter.cpp
Labels: enhancement

#7695 Add Lua tests on Github Windows build
  .github/workflows/build-mudlet-win.yml
  CI/setup-windows-sdk.sh
  src/main.cpp
  src/run-tests.xml
Labels: 🙋 Bounty claim

#7715 Fix notifing on new text when all the new text is deleted
  src/TConsole.cpp
  src/TConsole.h
  src/TMainConsole.cpp
  src/ctelnet.cpp
  src/ctelnet.h
Labels: 🙋 Bounty claim
